### ISSUE TITLE
Babashka fails to find 'clojure.main' after fresh installation of Clojure and Babashka

### ISSUE THREAD

**Issue by adkelley** [babashka/babashka#1070]
**version**
0.6.5

**platform**
Apple M1 MacBook Pro 2021, MacOs 12.0.1

**problem**
I upgraded to the new M1 MacBook Pro which required a fresh install of Clojure and Babashka.  I used homebrew to install both of them.  While bb scripts worked fine under the new install, I wasn't able to run my projects (i.e., `bb -m my-project.main`), including the [example project](https://book.babashka.org/#project-setup) from the Babashka book.  The error I encountered was `Could not find or load main class clojure.main` This error message seems to be coming from the JVM, perhaps because babashka is trying to download dependencies for which it uses clojure. 

I also noticed that, inside a Babashka project folder, `bb --version` failed with the same error, while it worked correctly outside of the project folder.   I tried `rm -rf ~/.deps.clj` which is created by bb, and I also tried `rm -rf  ~/.clojure/.cpcache` and that didn't solve it, either.  

Notably, both inside & outside a project directory `bb clojure --version` failed with an exception because it failed to find `~/.clojure/.cpcache/363A78F07197DB7FD0EDF27138B9FAFF.cp `

**workaround**
The apparent workaround was to copy the `bb.edn` file to `deps.edn`, run the program, then run it again using `bb`
```
$ cp bb.edn deps.edn
$ clojure -M -m my-project.main
{1 {:id 1}, 2 {:id 2}}
$ bb -m my-project.main
{1 {:id 1}, 2 {:id 2}}
```
This not only solved my problem running `my-project.main`, but all of my babashka projects, as well.  Perhaps the clojure bash script copied some file to the `.cpcache` that the bb one didn't, but this only speculation.

**repro**
Unfortunately, this is not reproducible.  I tried deleting `$HOME/.clojure/.cpcache` and `$HOME/.deps.edn` but `bb -m my-project.main` `bb --verson` worked correctly.  

However, `bb clojure --version` still raises an exception, failing to find `~/.clojure/.cpcache/363A78F07197DB7FD0EDF27138B9FAFF.cp ` so perhaps this might be related to my original problem.  I'll issue another bug report for `bb clojure --version`

**Comment by borkdude** [comment]
As I can't repro this, I will close, but will re-open once a repro is available. Thanks. At least we fixed the `--version` issue on master.

**Comment by adkelley** [comment]
No worries.  Thank you again for your assistance in getting me back up and running Babashka on my new Mac.

**Comment by sbenhaim** [comment]
I ran into a similar issue, found a resolution, and now also cannot reproduce 🙃. 

The fix was to delete the `~/.deps.clj/` folder and let babaska or neil re-install ClojureTools. So, I suspect the issue may be that some other tool is populating the `~/.deps.clj` directory with an incompatible version of ClojureTools or some other incompatible something.

## My Journey

On an Intel Mac using Homebrew, I installed `clojure`, then `bb`, then `neil`. When I ran `neil` for the first time, I got `Error: Could not find or load main class clojure.main`. (I can't be sure if ClojureTools were already installed before I ran neil for the first time.)

Same result when running `bb clojure`. `bb clojure --version` succeeded showing `Clojure CLI version (deps.clj) 1.11.1.1347`, but if the directory contained a `bb.edn` file, it failed with clojure.main not found again.

I deleted `~/.deps.clj`, ran `neil` again. It installed ClojureTools, and then all is working again.

Hopefully there's a helpful detail somewhere in there!

**Comment by borkdude** [comment]
Could you post all the output that bb produced, if you still have it around?

**Comment by jpe90** [comment]
I hit this on ubuntu in WSL following the [biff tutorial](https://biffweb.com/docs/tutorial/new-project/). I got the below error message when running `bb dev`. Deleting `~/.deps.clj` and then re-running `bb dev` worked.

Output from first failure:

```
Clojure tools not yet in expected location: /home/solaire/.deps.clj/1.11.1.1347/ClojureTools/clojure-tools-1.11.1.1347.jar
Unzipping /home/solaire/.deps.clj/1.11.1.1347/ClojureTools/tools.zip ...
Exception in thread "main" java.io.EOFException: Unexpected end of ZLIB input stream
        at java.base@19.0.2/java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:244)
        at java.base@19.0.2/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:159)
        at java.base@19.0.2/java.util.zip.ZipInputStream.read(ZipInputStream.java:196)
        at java.base@19.0.2/java.util.zip.CheckedInputStream.read(CheckedInputStream.java:82)
        at java.base@19.0.2/java.io.InputStream.transferTo(InputStream.java:790)
        at java.base@19.0.2/java.nio.file.Files.copy(Files.java:3170)
        at borkdude.deps$unzip.invokeStatic(deps.clj:408)
        at borkdude.deps$clojure_tools_install_BANG_.invokeStatic(deps.clj:549)
        at borkdude.deps$_main$fn__5991.invoke(deps.clj:842)
        at borkdude.deps$_main.invokeStatic(deps.clj:842)
        at borkdude.deps$_main.doInvoke(deps.clj:804)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at babashka.impl.deps$add_deps$fn__27055$fn__27056.invoke(deps.clj:106)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1990)
        at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1990)
        at clojure.lang.RestFn.invoke(RestFn.java:425)
        at babashka.impl.deps$add_deps$fn__27055.invoke(deps.clj:106)
        at babashka.impl.deps$add_deps.invokeStatic(deps.clj:106)
        at babashka.main$exec$fn__31821.invoke(main.clj:870)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1990)
        at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1990)
        at clojure.lang.RestFn.invoke(RestFn.java:425)
        at babashka.main$exec.invokeStatic(main.clj:822)
        at babashka.main$main.invokeStatic(main.clj:1165)
        at babashka.main$main.doInvoke(main.clj:1122)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at babashka.main$_main.invokeStatic(main.clj:1198)
        at babashka.main$_main.doInvoke(main.clj:1190)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at babashka.main.main(Unknown Source)
```

**Comment by sbenhaim** [comment]
With Babashka

```
$ bb clojure
Error: Could not find or load main class clojure.main
Caused by: java.lang.ClassNotFoundException: clojure.main
Exception in thread "main" clojure.lang.ExceptionInfo:  babashka.process.Process@29ad5bcd
	at babashka.process$check.invokeStatic(process.cljc:111)
	at babashka.process$shell.invokeStatic(process.cljc:646)
	at babashka.process$shell.doInvoke(process.cljc:624)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at babashka.impl.process$shell.invokeStatic(process.clj:27)
	at babashka.deps$clojure$fn__6032.invoke(deps.clj:41)
	at borkdude.deps$_main.invokeStatic(deps.clj:969)
	at borkdude.deps$_main.doInvoke(deps.clj:804)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at babashka.deps$clojure.invokeStatic(deps.clj:40)
	at babashka.main$exec$fn__31821.invoke(main.clj:1012)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1990)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1990)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at babashka.main$exec.invokeStatic(main.clj:822)
	at babashka.main$main.invokeStatic(main.clj:1165)
	at babashka.main$main.doInvoke(main.clj:1122)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at babashka.main$_main.invokeStatic(main.clj:1198)
	at babashka.main$_main.doInvoke(main.clj:1190)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at babashka.main.main(Unknown Source)
```

With neil

```
neil new --name ctrl
Error: Could not find or load main class clojure.main
Caused by: java.lang.ClassNotFoundException: clojure.main
----- Error --------------------------------------------------------------------
Type:     clojure.lang.ExceptionInfo
Message:
Data:     {:proc #object[java.lang.ProcessImpl 0x5cd6437a "Process[pid=52337, exitValue=1]"], :exit 1, :in #object[java.lang.ProcessBuilder$NullOutputStream 0x376b06c6 "java.lang.ProcessBuilder$NullOutputStream@376b06c6"], :out #object[java.lang.ProcessImpl$ProcessPipeInputStream 0x601e0c2d "java.lang.ProcessImpl$ProcessPipeInputStream@601e0c2d"], :err #object[java.lang.ProcessBuilder$NullInputStream 0x2c0656ac "java.lang.ProcessBuilder$NullInputStream@2c0656ac"], :prev nil, :cmd ["/usr/bin/java" "-XX:-OmitStackTraceInFastThrow" "-classpath" "/Users/selah/.deps.clj/1.11.1.1347/ClojureTools/clojure-tools-1.11.1.1347.jar" "clojure.main" "-m" "clojure.tools.deps.script.make-classpath2" "--config-user" "" "--config-project" "__babashka_no_deps_file__.edn" "--basis-file" "/Users/selah/.config/clojure/.cpcache/158BEBBC72DF2CC48E598157BC4F6490.basis" "--cp-file" "/Users/selah/.config/clojure/.cpcache/158BEBBC72DF2CC48E598157BC4F6490.cp" "--jvm-file" "/Users/selah/.config/clojure/.cpcache/158BEBBC72DF2CC48E598157BC4F6490.jvm" "--main-file" "/Users/selah/.config/clojure/.cpcache/158BEBBC72DF2CC48E598157BC4F6490.main" "--manifest-file" "/Users/selah/.config/clojure/.cpcache/158BEBBC72DF2CC48E598157BC4F6490.manifest" "--config-data" "{:deps {borkdude/rewrite-edn {:mvn/version \"0.4.6\"}, org.babashka/spec.alpha {:git/url \"https://github.com/babashka/spec.alpha\", :git/sha \"1a841c4cc1d4f6dab7505a98ed2d532dd9d56b78\"}, io.github.seancorfield/deps-new {:git/url \"https://github.com/seancorfield/deps-new\", :git/tag \"v0.5.0\", :git/sha \"48bf01e\"}, org.babashka/cli {:mvn/version \"0.6.45\"}, version-clj/version-clj {:mvn/version \"2.0.2\"}, org.babashka/http-client {:mvn/version \"0.1.4\"}}, :aliases {:org.babashka/defaults {:replace-paths [], :classpath-overrides {org.clojure/clojure \"\", org.clojure/spec.alpha \"\", org.clojure/core.specs.alpha \"\"}}}}" "-A::org.babashka/defaults"], :type :babashka.process/error}
Location: /usr/local/bin/neil:8:1

----- Context ------------------------------------------------------------------
 4: ;; DO NOT EDIT DIRECTLY. GENERATED FROM scr/babashka/neil.clj
 5:
 6: (require '[babashka.deps :as deps])
 7:
 8: (deps/add-deps '{:deps {borkdude/rewrite-edn {:mvn/version "0.4.6"}
    ^---
 9:                         org.babashka/spec.alpha {:git/url "https://github.com/babashka/spec.alpha"
10:                                                  :git/sha "1a841c4cc1d4f6dab7505a98ed2d532dd9d56b78"}
11:                         io.github.seancorfield/deps-new {:git/url "https://github.com/seancorfield/deps-new"
12:                                                          :git/tag "v0.5.0"
13:                                                          :git/sha "48bf01e"}

----- Stack trace --------------------------------------------------------------
babashka.process/check                          - <built-in>
babashka.process/shell                          - <built-in>
babashka.impl.deps/add-deps/fn--27048           - <built-in>
borkdude.deps/-main                             - <built-in>
clojure.core/apply                              - <built-in>
... (run with --debug to see elided elements)
clojure.core/apply                              - <built-in>
clojure.core/with-bindings*                     - <built-in>
babashka.impl.deps/add-deps/fn--27055           - <built-in>
babashka.impl.deps/add-deps                     - <built-in>
user                                            - /usr/local/bin/neil:8:1
```

**Comment by borkdude** [comment]
I hope to have a better fix in place for the next version of babashka.
You can already test this version with:

```
bash <(curl https://raw.githubusercontent.com/babashka/babashka/master/install) --dev-build --dir /tmp
```

but you first need to delete `~/.deps.clj` again
