### ISSUE TITLE
bb clojure --version raises an exception on Apple M1

### ISSUE THREAD

**Issue by adkelley** [babashka/babashka#1071]
**version**
0.6.5

**platform**
Apple M1 MacBook Pro 2021, MacOs 12.0.1

**problem**
`bb clojure --version` raises an exception, failing to find a '.cp' file in `~/.clojure/.cpcache/`

**repro**
```
$ bb clojure --version
Exception in thread "main" java.io.FileNotFoundException: ~/.clojure/.cpcache/363A78F07197DB7FD0EDF27138B9FAFF.cp (No such file or directory)
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST_FileNotFoundException_constructor_970c509c6abfd3f98898b9a7521945418b90b270(JNIJavaCallWrappers.java:0)
	at java.io.FileInputStream.open0(FileInputStream.java)
	at java.io.FileInputStream.open(FileInputStream.java:219)
	at java.io.FileInputStream.<init>(FileInputStream.java:157)
	at clojure.java.io$fn__11522.invokeStatic(io.clj:229)
	at clojure.java.io$fn__11522.invoke(io.clj:229)
	at clojure.java.io$fn__11435$G__11428__11442.invoke(io.clj:69)
	at clojure.java.io$fn__11496.invokeStatic(io.clj:165)
	at clojure.java.io$fn__11496.invoke(io.clj:165)
	at clojure.java.io$fn__11448$G__11424__11455.invoke(io.clj:69)
	at clojure.java.io$reader.invokeStatic(io.clj:102)
	at clojure.java.io$reader.doInvoke(io.clj:86)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$slurp.invokeStatic(core.clj:6967)
	at clojure.core$slurp.doInvoke(core.clj:6967)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at borkdude.deps$_main.invokeStatic(deps.clj:646)
	at borkdude.deps$_main.doInvoke(deps.clj:425)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at babashka.deps$clojure.invokeStatic(deps.clj:42)
	at babashka.deps$clojure.invoke(deps.clj:6)
	at babashka.deps$clojure.invokeStatic(deps.clj:30)
	at babashka.main$exec.invokeStatic(main.clj:808)
	at babashka.main$main.invokeStatic(main.clj:900)
	at babashka.main$main.doInvoke(main.clj:887)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at babashka.main$_main.invokeStatic(main.clj:934)
	at babashka.main$_main.doInvoke(main.clj:926)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at babashka.main.main(Unknown Source)
```
**expected behavior**
```
$ bb clojure --version
Clojure CLI version 1.10.3.1029
```

**Comment by borkdude** [comment]
Thanks for posting the issue. Can you also specify the `java` version? And can you specify if your `java` version is running natively on M1 or also under Rosetta2 like babashka?

**Comment by borkdude** [comment]
I could reproduce this issue locally by first doing `rm -rf .cpcache` in the local directory.
Then `bb clojure --version` gives the issue. 
But after executing `bb clojure`, then `bb clojure --version` worked.

**Comment by adkelley** [comment]
> Thanks for posting the issue. Can you also specify the `java` version? And can you specify if your `java` version is running natively on M1 or also under Rosetta2 like babashka?

openjdk 17.0.1 2021-10-19
OpenJDK Runtime Environment Homebrew (build 17.0.1+0)
OpenJDK 64-Bit Server VM Homebrew (build 17.0.1+0, mixed mode, sharing)

Not sure how to determine whether it's native on M1.  I'll update this response if I can determine it.

> I could reproduce this issue locally by first doing `rm -rf .cpcache` in the local directory.
> Then `bb clojure --version` gives the issue.
> But after executing `bb clojure`, then `bb clojure --version` worked.

Yes, I can reproduce the same result.
