### ISSUE TITLE
self-signed certificat in chain makes bb unusable

### ISSUE THREAD

**Issue by xificurC** [babashka/babashka#1073]
**version**

babashka v0.6.4

**platform**

Linux

**problem**

Running anything with a fresh install fails. The problem seems to be that bb wants to download a jar but can't because of a company self-signed certificate in the chain. On a JDK this is fixed by importing the certificate via `keytool`.

**repro**

```clj
bb generate-values values.clj
Could not find /home/xxx/.deps.clj/1.10.3.1029/ClojureTools/clojure-tools-1.10.3.1029.jar
Downloading tools jar from https://download.clojure.org/install/clojure-tools-1.10.3.1029.zip to /home/xxx/.deps.clj/1.10.3.1029/ClojureTools
Exception in thread "main" javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.ssl.Alert.createSSLException(Alert.java:131)
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:349)
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:292)
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:287)
        at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:654)
        at sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473)
        at sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369)
        at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
        at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
        at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:421)
        at sun.security.ssl.TransportContext.dispatch(TransportContext.java:182)
        at sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
        at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1426)
        at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1336)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:450)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:421)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:572)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:197)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:168)
        at borkdude.deps$download.invokeStatic(deps.clj:229)
        at borkdude.deps$clojure_tools_jar_download.invokeStatic(deps.clj:255)
        at borkdude.deps$_main$fn__9568.invoke(deps.clj:467)
        at borkdude.deps$_main.invokeStatic(deps.clj:467)
        at borkdude.deps$_main.doInvoke(deps.clj:425)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at babashka.impl.deps$add_deps$fn__29985$fn__29986.invoke(deps.clj:73)
        at babashka.impl.deps$add_deps$fn__29985.invoke(deps.clj:73)
        at babashka.impl.deps$add_deps.invokeStatic(deps.clj:73)
        at babashka.main$exec.invokeStatic(main.clj:704)
        at babashka.main$main.invokeStatic(main.clj:900)
        at babashka.main$main.doInvoke(main.clj:887)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at babashka.main$_main.invokeStatic(main.clj:934)
        at babashka.main$_main.doInvoke(main.clj:926)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at babashka.main.main(Unknown Source)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
        at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
        at sun.security.validator.Validator.validate(Validator.java:264)
        at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:313)
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:222)
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129)
        at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:638)
        ... 33 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
        at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
        at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
        ... 39 more
```

**expected behavior**

The expectation is that either

- a certificate can be included
- the global certificate chain is used (on ubuntu this is /etc/ssl/certs/ca-certificates.crt)
- the used set of certificates is customizable

**Comment by borkdude** [comment]
@xificurC You should be able to launch babashka with a property as described here:

https://www.graalvm.org/reference-manual/native-image/CertificateManagement/

```
bb -Djavax.net.ssl.trustStore=...
```

Also see this issue: https://github.com/babashka/babashka/issues/1052

Let me know how that goes.

**Comment by jijun99** [comment]
Is it possible to specify the property in bb.edn? So that I do not need to add in command line option for bb. Thanks.
