### ISSUE TITLE
babashka faild with bb.edn and without java

### ISSUE THREAD

**Issue by zohar-cyc** [babashka/babashka#1123]
**version**
babashka v0.7.2

**platform**
Linux x64

**problem**

Running babashka 0.7.2 in an environment with no java installed, when there's a `bb.edn` file, fails with this message:
```
Exception in thread "main" java.lang.Exception: Couldn't find 'java'. Please set JAVA_HOME.
at borkdude.deps$_main.invokeStatic(deps.clj:436)
at borkdude.deps$_main.doInvoke(deps.clj:425)
at clojure.lang.RestFn.applyTo(RestFn.java:137)
at clojure.core$apply.invokeStatic(core.clj:667)
at babashka.impl.deps$add_deps$fn__30367$fn__30368.invoke(deps.clj:88)
at babashka.impl.deps$add_deps$fn__30367.invoke(deps.clj:88)
at babashka.impl.deps$add_deps.invokeStatic(deps.clj:88)
at babashka.main$exec.invokeStatic(main.clj:722)
at babashka.main$main.invokeStatic(main.clj:940)
at babashka.main$main.doInvoke(main.clj:921)
at clojure.lang.RestFn.applyTo(RestFn.java:137)
at clojure.core$apply.invokeStatic(core.clj:667)
at babashka.main$_main.invokeStatic(main.clj:973)
at babashka.main$_main.doInvoke(main.clj:965)
at clojure.lang.RestFn.applyTo(RestFn.java:137)
at babashka.main.main(Unknown Source)
```

Version 0.7.0 worked fine.

**repro**
```shell
docker run --rm -it python:3.9

bash -c "$(curl -fsSL https://raw.githubusercontent.com/babashka/babashka/master/install)"
echo '{}' > bb.edn
bb
```

**expected behavior**
Should run in an environment without java

**Comment by borkdude** [comment]
Thanks, will look into it.

**Comment by borkdude** [comment]
0.7.3 is building

**Comment by borkdude** [comment]
Released!
