### ISSUE TITLE
java.nio.file.InvalidPathException using caxa

### ISSUE THREAD

**Issue by MrGung** [babashka/babashka#1186]
[ To keep development of this project going, consider sponsoring. If you are
already a sponsor, thank you! ]

**version**

0.7.5

**platform**

Windows

**problem**

Bundling with `npx caxa --input bundle --output orch.exe --no-include-node -- "{{caxa}}\bb.exe" "-cp {{caxa}}\bbg.jar" "--config {{caxa}}\lovoonl-orch.edn"`

And calling `orch.exe`, I get

```
Exception in thread "main" java.io.IOException: java.nio.file.InvalidPathException: Illegal char <:> at index 5: -cp D:\Users\Steffen\AppData\Local\Temp\caxa\applications\orch\uzi33hkpy5\0\bbg.jar
        at java.util.zip.ZipFile$Source.get(ZipFile.java:1261)
        at java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:733)
        at java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:850)
        at java.util.zip.ZipFile.<init>(ZipFile.java:248)
        at java.util.zip.ZipFile.<init>(ZipFile.java:177)
        at java.util.jar.JarFile.<init>(JarFile.java:350)
        at java.util.jar.JarFile.<init>(JarFile.java:321)
        at java.util.jar.JarFile.<init>(JarFile.java:287)
        at babashka.impl.classpath$path_from_jar.invokeStatic(classpath.clj:30)
        at babashka.impl.classpath.JarFileResolver.getResource(classpath.clj:43)
        at babashka.impl.classpath.Loader$fn__17567.invoke(classpath.clj:57)
        at clojure.core$some.invokeStatic(core.clj:2718)
        at babashka.impl.classpath.Loader.getResource(classpath.clj:54)
        at babashka.main$exec.invokeStatic(main.clj:759)
        at babashka.main$main.invokeStatic(main.clj:944)
        at babashka.main$main.doInvoke(main.clj:925)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at babashka.main$_main.invokeStatic(main.clj:977)
        at babashka.main$_main.doInvoke(main.clj:969)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at babashka.main.main(Unknown Source)
Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 5: -cp D:\Users\Steffen\AppData\Local\Temp\caxa\applications\orch\uzi33hkpy5\0\bbg.jar
        at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
        at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
        at java.io.File.toPath(File.java:2329)
        at java.util.zip.ZipFile$Source.get(ZipFile.java:1259)
        ... 21 more
```

whereas calling `bb -cp D:\Users\Steffen\AppData\Local\Temp\caxa\applications\orch\uzi33hkpy5\0\bbg.jar` starts a REPL, as expected.

I am not sure whether that's a problem located at caxa's, or bb - but I guess the latter. ;-)
**repro**

[ Please provide a minimal working reproduction of the problem ]

**expected behavior**

[ What is the behavior you expected to see? Please provide a minimal working example ]

**Comment by borkdude** [comment]
Can you try splitting the arguments? `"cp" ".."`? Right now you have concatenated them.

**Comment by borkdude** [comment]
Same with `--config` btw, split it into multiple command line arguments rather than combining into one string.

**Comment by borkdude** [comment]
Another tip: when you run it multiple times, caxa will include the binary that it already wrote. Make sure to remove everything before running again. I'll add both things to the wiki.
