### ISSUE TITLE
Unable to build binary with BABASHKA_FEATURE_POSTGRESQL feature

### ISSUE THREAD

**Issue by neuromantik33** [babashka/babashka#1343]
**version**
```bash
$ git status
HEAD detached at v0.9.161
nothing to commit, working tree clean
```
**platform**
```bash
$ uname -a
Linux drnick-xps-15-9500 5.15.0-46-generic #49~20.04.1-Ubuntu SMP Thu Aug 4 19:15:44 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
**problem**
I'm unable to build the latest tagged babashka binary with the `BABASHKA_FEATURE_POSTGRESQL` feature set to `true`.
The build output is the following:
```
...
Step 54/60 : RUN ./script/setup-musl
 ---> Running in 47b2c9dbf0d6
BABASHKA_STATIC wasn't set, skipping musl installation.
Removing intermediate container 47b2c9dbf0d6
 ---> 1ff72b52143f
Step 55/60 : RUN ./script/compile
 ---> Running in 359d66f70f69
Downloading: Component catalog from www.graalvm.org
Processing Component: Native Image
Downloading: Component native-image: Native Image from github.com
Installing new component: Native Image (org.graalvm.native-image, version 22.2.0)
Apply jar:file:///opt/target/babashka-0.9.161-standalone.jar!/META-INF/native-image/http-kit/http-kit/native-image.properties
Apply jar:file:///opt/target/babashka-0.9.161-standalone.jar!/META-INF/native-image/babashka/babashka/native-image.properties
Warning: Ignoring server-mode native-image argument --no-server.
Apply jar:file:///opt/target/babashka-0.9.161-standalone.jar!/META-INF/native-image/babashka/babashka/reflect-config.json
Executing [
/opt/graalvm-ce-java11-22.2.0/bin/java \
-XX:+UseParallelGC \
-XX:+UnlockExperimentalVMOptions \
-XX:+EnableJVMCI \
-Dtruffle.TrustAllTruffleRuntimeProviders=true \
-Dtruffle.TruffleRuntime=com.oracle.truffle.api.impl.DefaultTruffleRuntime \
-Dgraalvm.ForcePolyglotInvalid=true \
-Dgraalvm.locatorDisabled=true \
-Dsubstratevm.IgnoreGraalVersionCheck=true \
--add-exports=java.base/com.sun.crypto.provider=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.event=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.loader=org.graalvm.nativeimage.builder,org.graalvm.truffle \
--add-exports=java.base/jdk.internal.logger=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.misc=org.graalvm.nativeimage.builder,org.graalvm.nativeimage.objectfile \
--add-exports=java.base/jdk.internal.module=jdk.internal.vm.compiler,org.graalvm.nativeimage.base,org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.org.objectweb.asm=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.perf=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.ref=org.graalvm.nativeimage.builder,org.graalvm.nativeimage.objectfile \
--add-exports=java.base/jdk.internal.reflect=org.graalvm.nativeimage.builder \
--add-exports=java.base/jdk.internal.vm.annotation=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.invoke.util=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.net=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.nio.ch=org.graalvm.nativeimage.builder,org.graalvm.nativeimage.objectfile \
--add-exports=java.base/sun.reflect.annotation=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.reflect.generics.factory=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.reflect.generics.reflectiveObjects=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.reflect.generics.repository=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.reflect.generics.scope=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.reflect.generics.tree=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.security.jca=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.security.provider=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.security.ssl=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.security.util=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.security.x509=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.text.spi=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.util.calendar=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.util.cldr=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.util.locale.provider=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.util.locale=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.util.resources=org.graalvm.nativeimage.builder \
--add-exports=java.base/sun.util=org.graalvm.nativeimage.builder \
--add-exports=java.desktop/sun.java2d.pipe=org.graalvm.nativeimage.builder \
--add-exports=java.desktop/sun.java2d=org.graalvm.nativeimage.builder \
--add-exports=java.management/com.sun.jmx.mbeanserver=org.graalvm.nativeimage.builder \
--add-exports=java.management/sun.management=org.graalvm.nativeimage.builder,org.graalvm.nativeimage.pointsto \
--add-exports=java.xml.crypto/org.jcp.xml.dsig.internal.dom=org.graalvm.nativeimage.builder \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.aarch64=jdk.internal.vm.compiler,org.graalvm.nativeimage.builder,org.graalvm.nativeimage.objectfile \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.amd64=jdk.internal.vm.compiler,org.graalvm.nativeimage.builder,org.graalvm.nativeimage.objectfile \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code.site=jdk.internal.vm.compiler,org.graalvm.nativeimage.builder,org.graalvm.nativeimage.llvm \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code.stack=jdk.internal.vm.compiler,org.graalvm.nativeimage.builder \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.code=jdk.internal.vm.compiler,org.graalvm.nativeimage.builder,org.graalvm.nativeimage.llvm,org.graalvm.nativeimage.objectfile,org.graalvm.nativeimage.pointsto \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.common=jdk.internal.vm.compiler,org.graalvm.nativeimage.builder,org.graalvm.nativeimage.pointsto \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot.aarch64=jdk.internal.vm.compiler \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot.amd64=jdk.internal.vm.compiler \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot.sparc=jdk.internal.vm.compiler \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.hotspot=jdk.internal.vm.compiler,org.graalvm.nativeimage.builder \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.meta=jdk.internal.vm.compiler,org.graalvm.nativeimage.builder,org.graalvm.nativeimage.llvm,org.graalvm.nativeimage.objectfile,org.graalvm.nativeimage.pointsto \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.runtime=jdk.internal.vm.compiler,org.graalvm.nativeimage.builder,org.graalvm.nativeimage.pointsto \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.services=jdk.internal.vm.compiler,org.graalvm.nativeimage.builder \
--add-exports=jdk.internal.vm.ci/jdk.vm.ci.sparc=jdk.internal.vm.compiler \
--add-exports=jdk.jfr/jdk.jfr.events=org.graalvm.nativeimage.builder \
--add-exports=jdk.jfr/jdk.jfr.internal.handlers=org.graalvm.nativeimage.builder \
--add-exports=jdk.jfr/jdk.jfr.internal.jfc=org.graalvm.nativeimage.builder \
--add-exports=jdk.jfr/jdk.jfr.internal=org.graalvm.nativeimage.builder \
--add-exports=jdk.management/com.sun.management.internal=org.graalvm.nativeimage.builder \
-XX:+UseJVMCINativeLibrary \
-Xss10m \
-Xms1g \
-Xmx14g \
-Djava.awt.headless=true \
-Dorg.graalvm.version=22.2.0 \
-Dcom.oracle.graalvm.isaot=true \
-Djava.system.class.loader=com.oracle.svm.hosted.NativeImageSystemClassLoader \
-Xshare:off \
-Djdk.internal.lambda.disableEagerInitialization=true \
-Djdk.internal.lambda.eagerlyInitialize=false \
-Djava.lang.invoke.InnerClassLambdaMetafactory.initializeLambdas=false \
-Dborkdude.dynaload.aot=true \
-Xmx4500m \
-javaagent:/opt/graalvm-ce-java11-22.2.0/lib/svm/builder/svm.jar \
--module-path \
/opt/graalvm-ce-java11-22.2.0/lib/truffle/truffle-api.jar:/opt/graalvm-ce-java11-22.2.0/lib/svm/builder/javacpp-platform-specific-shadowed.jar:/opt/graalvm-ce-java11-22.2.0/lib/svm/builder/javacpp-shadowed.jar:/opt/graalvm-ce-java11-22.2.0/lib/svm/builder/pointsto.jar:/opt/graalvm-ce-java11-22.2.0/lib/svm/builder/llvm-wrapper-shadowed.jar:/opt/graalvm-ce-java11-22.2.0/lib/svm/builder/native-image-base.jar:/opt/graalvm-ce-java11-22.2.0/lib/svm/builder/svm.jar:/opt/graalvm-ce-java11-22.2.0/lib/svm/builder/svm-llvm.jar:/opt/graalvm-ce-java11-22.2.0/lib/svm/builder/llvm-platform-specific-shadowed.jar:/opt/graalvm-ce-java11-22.2.0/lib/svm/builder/objectfile.jar \
--module \
org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner \
-watchpid \
22 \
-imagecp \
/opt/target/babashka-0.9.161-standalone.jar \
-imagemp \
/opt/graalvm-ce-java11-22.2.0/lib/svm/library-support.jar \
-H:CLibraryPath=/opt/graalvm-ce-java11-22.2.0/lib/svm/clibraries/linux-amd64 \
-H:Path=/opt \
'-H:Class@manifest from file:///opt/target/babashka-0.9.161-standalone.jar=babashka.main' \
'-H:Name@manifest from file:///opt/target/babashka-0.9.161-standalone.jar=babashka-0.9.161-standalone' \
'-H:ClassInitialization@jar:file:///opt/target/babashka-0.9.161-standalone.jar!/META-INF/native-image/http-kit/http-kit/native-image.properties=org.httpkit.client.ClientSslEngineFactory$SSLHolder:run_time' \
'-H:Name@jar:file:///opt/target/babashka-0.9.161-standalone.jar!/META-INF/native-image/babashka/babashka/native-image.properties=bb' \
'-H:+ReportExceptionStackTraces@jar:file:///opt/target/babashka-0.9.161-standalone.jar!/META-INF/native-image/babashka/babashka/native-image.properties' \
'-H:IncludeResources@jar:file:///opt/target/babashka-0.9.161-standalone.jar!/META-INF/native-image/babashka/babashka/native-image.properties=BABASHKA_VERSION' \
'-H:IncludeResources@jar:file:///opt/target/babashka-0.9.161-standalone.jar!/META-INF/native-image/babashka/babashka/native-image.properties=META-INF/babashka/.*' \
'-H:IncludeResources@jar:file:///opt/target/babashka-0.9.161-standalone.jar!/META-INF/native-image/babashka/babashka/native-image.properties=SCI_VERSION' \
'-H:Log@jar:file:///opt/target/babashka-0.9.161-standalone.jar!/META-INF/native-image/babashka/babashka/native-image.properties=registerResource:' \
'-H:EnableURLProtocols@jar:file:///opt/target/babashka-0.9.161-standalone.jar!/META-INF/native-image/babashka/babashka/native-image.properties=http,https,jar' \
'-H:+EnableAllSecurityServices@jar:file:///opt/target/babashka-0.9.161-standalone.jar!/META-INF/native-image/babashka/babashka/native-image.properties' \
'-H:+JNI@jar:file:///opt/target/babashka-0.9.161-standalone.jar!/META-INF/native-image/babashka/babashka/native-image.properties' \
'-H:+ReportUnsupportedElementsAtRuntime@jar:file:///opt/target/babashka-0.9.161-standalone.jar!/META-INF/native-image/babashka/babashka/native-image.properties' \
'-H:ClassInitialization@jar:file:///opt/target/babashka-0.9.161-standalone.jar!/META-INF/native-image/babashka/babashka/native-image.properties=com.fasterxml.jackson:build_time' \
'-H:ClassInitialization@jar:file:///opt/target/babashka-0.9.161-standalone.jar!/META-INF/native-image/babashka/babashka/native-image.properties=java.sql.SQLException:build_time' \
'-H:ClassInitialization@jar:file:///opt/target/babashka-0.9.161-standalone.jar!/META-INF/native-image/babashka/babashka/native-image.properties=org.yaml.snakeyaml:build_time' \
'-H:ClassInitialization@jar:file:///opt/target/babashka-0.9.161-standalone.jar!/META-INF/native-image/babashka/babashka/native-image.properties=org.postgresql.sspi.SSPIClient:run_time' \
'-H:ClassInitialization@jar:file:///opt/target/babashka-0.9.161-standalone.jar!/META-INF/native-image/babashka/babashka/native-image.properties=org.httpkit.client.ClientSslEngineFactory$SSLHolder:run_time' \
'-H:ServiceLoaderFeatureExcludeServices@jar:file:///opt/target/babashka-0.9.161-standalone.jar!/META-INF/native-image/babashka/babashka/native-image.properties=javax.sound.sampled.spi.AudioFileReader' \
'-H:ServiceLoaderFeatureExcludeServices@jar:file:///opt/target/babashka-0.9.161-standalone.jar!/META-INF/native-image/babashka/babashka/native-image.properties=javax.sound.midi.spi.MidiFileReader' \
'-H:ServiceLoaderFeatureExcludeServices@jar:file:///opt/target/babashka-0.9.161-standalone.jar!/META-INF/native-image/babashka/babashka/native-image.properties=javax.sound.sampled.spi.MixerProvider' \
'-H:ServiceLoaderFeatureExcludeServices@jar:file:///opt/target/babashka-0.9.161-standalone.jar!/META-INF/native-image/babashka/babashka/native-image.properties=javax.sound.sampled.spi.FormatConversionProvider' \
'-H:ServiceLoaderFeatureExcludeServices@jar:file:///opt/target/babashka-0.9.161-standalone.jar!/META-INF/native-image/babashka/babashka/native-image.properties=javax.sound.sampled.spi.AudioFileWriter' \
'-H:ServiceLoaderFeatureExcludeServices@jar:file:///opt/target/babashka-0.9.161-standalone.jar!/META-INF/native-image/babashka/babashka/native-image.properties=javax.sound.midi.spi.MidiDeviceProvider' \
'-H:ServiceLoaderFeatureExcludeServices@jar:file:///opt/target/babashka-0.9.161-standalone.jar!/META-INF/native-image/babashka/babashka/native-image.properties=javax.sound.midi.spi.SoundbankReader' \
'-H:ServiceLoaderFeatureExcludeServices@jar:file:///opt/target/babashka-0.9.161-standalone.jar!/META-INF/native-image/babashka/babashka/native-image.properties=javax.sound.midi.spi.MidiFileWriter' \
'-H:ServiceLoaderFeatureExcludeServices@jar:file:///opt/target/babashka-0.9.161-standalone.jar!/META-INF/native-image/babashka/babashka/native-image.properties=java.net.ContentHandlerFactory' \
'-H:ServiceLoaderFeatureExcludeServices@jar:file:///opt/target/babashka-0.9.161-standalone.jar!/META-INF/native-image/babashka/babashka/native-image.properties=java.nio.charset.spi.CharsetProvider' \
'-H:ReflectionConfigurationResources@jar:file:///opt/target/babashka-0.9.161-standalone.jar!/META-INF/native-image/babashka/babashka/reflect-config.json=META-INF/native-image/babashka/babashka/reflect-config.json' \
-H:Name=bb \
-H:+ReportExceptionStackTraces \
-H:ReportAnalysisForbiddenType=java.awt.Toolkit:InHeap,Allocated \
-H:FallbackThreshold=0 \
-H:+DumpTargetInfo
]
WARNING: Unknown module: org.graalvm.nativeimage.llvm specified to --add-exports
WARNING: Unknown module: org.graalvm.nativeimage.llvm specified to --add-exports
WARNING: Unknown module: org.graalvm.nativeimage.llvm specified to --add-exports
Warning: Option 'EnableAllSecurityServices' is deprecated and might be removed from future versions
========================================================================================================================
GraalVM Native Image: Generating 'bb' (executable)...
========================================================================================================================
The URL protocol jar is not tested and might not work as expected.
Supported URL protocols enabled by default: file,resource. Supported URL protocols available on demand: http,https.
Registering packages for build time initialization: clojure, cognitect, bencode, borkdude, next, selmer, sci, aaaa_this_has_to_be_first, io.aviso, hf.depstar, org.httpkit, cheshire, clj_yaml, babashka, hiccup, edamame, taoensso, clj_easy, flatland.ordered, rewrite_clj
[1/7] Initializing...                                                                                    (6.5s @ 0.28GB)
 Version info: 'GraalVM 22.2.0 Java 11 CE'
 Java version info: '11.0.16+8-jvmci-22.2-b06'
 C compiler: gcc (linux, x86_64, 10.2.1)
 Garbage collector: Serial GC
 1 user-specific feature(s)
 - InitAtBuildTimeFeature
# Printing compilation-target information to: /opt/reports/target_info_20220823_131218.txt
To see how the classes got initialized, use --trace-class-initialization=org.postgresql.PGProperty
[2/7] Performing analysis...  []                                                                        (18.8s @ 1.55GB)
  11,941 (95.51%) of 12,502 classes reachable
  17,282 (49.78%) of 34,718 fields reachable
  42,426 (76.24%) of 55,645 methods reachable
     626 classes,     0 fields, and     0 methods registered for reflection
       2 native libraries: m, stdc++

Error: Classes that should be initialized at run time got initialized during image building:
 org.postgresql.PGProperty was unintentionally initialized at build time. To see why org.postgresql.PGProperty got initialized use --trace-class-initialization=org.postgresql.PGProperty

com.oracle.svm.core.util.UserError$UserException: Classes that should be initialized at run time got initialized during image building:
 org.postgresql.PGProperty was unintentionally initialized at build time. To see why org.postgresql.PGProperty got initialized use --trace-class-initialization=org.postgresql.PGProperty

	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:72)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.checkDelayedInitialization(ConfigurableClassInitialization.java:554)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.duringAnalysis(ClassInitializationFeature.java:172)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$10(NativeImageGenerator.java:734)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:78)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$11(NativeImageGenerator.java:734)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.PointsToAnalysis.runAnalysis(PointsToAnalysis.java:755)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:731)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:564)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:521)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:407)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:585)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
------------------------------------------------------------------------------------------------------------------------
                        2.2s (8.4% of total time) in 28 GCs | Peak RSS: 2.63GB | CPU load: 8.07
========================================================================================================================
Failed generating 'bb' after 25.5s.
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
	at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1716)
	at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1413)
	at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1374)
	at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1361)
The command '/bin/sh -c ./script/compile' returned a non-zero code: 1
```
**repro**
```bash
$ git checkout v0.9.161
$ git status
HEAD detached at v0.9.161
nothing to commit, working tree clean
$ docker build -t bb --build-arg BABASHKA_FEATURE_JDBC=true --build-arg BABASHKA_FEATURE_POSTGRESQL=true .
```
**expected behavior**
The build should succeed (I use bb for many postgresql related tasks).

**Comment by borkdude** [comment]
Can you try with the master version?
