### ISSUE TITLE
UnknownHostException trying to download clojure tools

### ISSUE THREAD

**Issue by svantevonerichsen6906** [babashka/babashka#1363]
**version** Babashka v0.9.162

**platform** `Linux <hostname> 5.19.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 08 Sep 2022 18:07:42 +0000 x86_64 GNU/Linux`

**problem**

On a freshly installed Arch Linux system with Clojure 1.11.1 and Babashka 10.9.162 installed, when encountering a bb.edn with a `:deps` section, Babashka tries to download clojure-tools, but cannot find the host.  Manual download and unzipping of the link shown in the exception works, and is a workaround.

**repro**

- Move clojure-tools away: `mv ~/.deps.clj/1.11.1.1155/ClojureTools ~/tmp/`
- Create an empty project with just a bb.edn: `{:deps []}`
- Run `bb tasks`

```
Clojure tools not yet in expected location: /home/<user>/.deps.clj/1.11.1.1155/ClojureTools/clojure-tools-1.11.1.1155.jar
Downloading https://download.clojure.org/install/clojure-tools-1.11.1.1155.zip to /home/<user>/.deps.clj/1.11.1.1155/ClojureTools
Exception in thread "main" java.net.UnknownHostException: download.clojure.org
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:229)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:609)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:305)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:182)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:508)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:603)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:373)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:207)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:193)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:168)
	at borkdude.deps$download.invokeStatic(deps.clj:229)
	at borkdude.deps$clojure_tools_jar_download.invokeStatic(deps.clj:255)
	at borkdude.deps$_main$fn__6418.invoke(deps.clj:466)
	at borkdude.deps$_main.invokeStatic(deps.clj:466)
	at borkdude.deps$_main.doInvoke(deps.clj:428)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at babashka.impl.deps$add_deps$fn__26653$fn__26654.invoke(deps.clj:92)
	at babashka.impl.deps$add_deps$fn__26653.invoke(deps.clj:92)
	at babashka.impl.deps$add_deps.invokeStatic(deps.clj:92)
	at babashka.main$exec.invokeStatic(main.clj:789)
	at babashka.main$main.invokeStatic(main.clj:1052)
	at babashka.main$main.doInvoke(main.clj:1027)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at babashka.main$_main$f__31113__auto____31123.invoke(main.clj:1091)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.lang.Thread.run(Thread.java:829)
	at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:705)
	at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202)
Exception in thread "main" java.lang.NullPointerException
	at clojure.lang.RT.intCast(RT.java:1221)
	at babashka.main$_main.invokeStatic(main.clj:1091)
	at babashka.main$_main.doInvoke(main.clj:1077)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at babashka.main.main(Unknown Source)
```

**expected behavior**

clojure-tools is downloaded, babashka shows tasks.

**workaround**

Manually download the shown ZIP file and unzip it to the expected location.  (Kudos for the clear error message.)

**Comment by borkdude** [comment]
@svantevonerichsen6906 Is it possible to make e.g. a Dockerfile where this manifests? I don't have access to an Arch system where I can easily repro this.

**Comment by svantevonerichsen6906** [comment]
Thanks for the quick reply.  My docker is not yet set up, so this might take a bit.  It should be something like https://github.com/testcab/docker-yay/blob/master/Dockerfile and then `yay -Syu clojure babashka-bin` to set up.  Then `RUN echo '{:deps []}' > bb.edn` and `bb tasks`.

**Comment by svantevonerichsen6906** [comment]
We tried to reproduce it in a docker container, but without success.  It seems to be a problem only on my machine.  I can work for now with the workaround, will try to debug for better hypotheses later.

I guess this could be closed for now.

**Comment by borkdude** [comment]
Feel free to re-open as necessary.

**Comment by nivekuil** [comment]
ran into this on a fresh Arch install, realized that I forgot to `sudo ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf` -- you have to do this for compatibility with stuff that reads /etc/resolv.conf directly instead of getaddrinfo.
