### ISSUE TITLE
bb clojure -M -e "*clojure-version*" failed

### ISSUE THREAD

**Issue by sg-qwt** [babashka/babashka#1533]
By following the babashka book [example](https://book.babashka.org/#_invoking_clojure) and run command
`bb clojure -M -e "*clojure-version*"`

I got following error:
```
Clojure tools not yet in expected location: /home/me/.deps.clj/1.11.1.1257/ClojureTools/clojure-tools-1.11.1.1257.jar                  
Downloading https://download.clojure.org/install/clojure-tools-1.11.1.1257.zip to /home/me/.deps.clj/1.11.1.1257/ClojureTools/tools.zip
Unzipping /home/me/.deps.clj/1.11.1.1257/ClojureTools/tools.zip ...                                       
Exception in thread "main" java.io.EOFException: Unexpected end of ZLIB input stream                      
        at java.base@19.0.2/java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:244)          
        at java.base@19.0.2/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:159)          
        at java.base@19.0.2/java.util.zip.ZipInputStream.read(ZipInputStream.java:196)                    
        at java.base@19.0.2/java.io.InputStream.transferTo(InputStream.java:790)                          
        at java.base@19.0.2/java.nio.file.Files.copy(Files.java:3170)                                     
        at borkdude.deps$unzip.invokeStatic(deps.clj:320)                                                                                                                                                            
        at borkdude.deps$clojure_tools_jar_download.invokeStatic(deps.clj:414)                            
        at borkdude.deps$_main$fn__5900.invoke(deps.clj:635)                                              
        at borkdude.deps$_main.invokeStatic(deps.clj:633)                                                 
        at borkdude.deps$_main.doInvoke(deps.clj:588)                                                     
        at clojure.lang.RestFn.applyTo(RestFn.java:137)                                                   
        at clojure.core$apply.invokeStatic(core.clj:667)                                                  
        at babashka.deps$clojure.invokeStatic(deps.clj:42)                                                                                                                                                           
        at babashka.main$exec$fn__31650.invoke(main.clj:1014)                                             
        at clojure.lang.AFn.applyToHelper(AFn.java:152)                                                   
        at clojure.lang.AFn.applyTo(AFn.java:144)                                                                                                                                                                    
        at clojure.core$apply.invokeStatic(core.clj:667)                                                  
        at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1990)                                   
        at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1990)                                       
        at clojure.lang.RestFn.invoke(RestFn.java:425)                                                                                                                                                               
        at babashka.main$exec.invokeStatic(main.clj:824)                                                  
        at babashka.main$main.invokeStatic(main.clj:1155)                                                 
        at babashka.main$main.doInvoke(main.clj:1124)                                                     
        at clojure.lang.RestFn.applyTo(RestFn.java:137)                                                   
        at clojure.core$apply.invokeStatic(core.clj:667)                                                  
        at babashka.main$_main.invokeStatic(main.clj:1188)                                                
        at babashka.main$_main.doInvoke(main.clj:1180)                                                    
        at clojure.lang.RestFn.applyTo(RestFn.java:137)                                                   
        at babashka.main.main(Unknown Source)   
```

**version**

babashka v1.3.176

Clojure CLI version 1.11.1.1257

java --version
openjdk 11.0.18 2023-01-17
OpenJDK Runtime Environment (build 11.0.18+0-adhoc..source)
OpenJDK 64-Bit Server VM (build 11.0.18+0-adhoc..source, mixed mode)

**platform**
Linux 6.1.20 NixOS x86_64 GNU/Linux

**Comment by borkdude** [comment]
It looks like the zip file you downloaded is corrupt.
Can you try to delete `~/.deps.clj` and try again?

**Comment by sg-qwt** [comment]
> It looks like the zip file you downloaded is corrupt. Can you try to delete `~/.deps.clj` and try again?

You're right! Thanks for the quick reply. My network in behind vpn and it seems that's the culprit this case. After trying to disabe vpn and clean up ~/.deps.clj and rerun, it'd succeed and go through.
