### ISSUE TITLE
Handle deps.clj corrupt tools jar error

### ISSUE THREAD

**Issue by borkdude** [babashka/babashka#1576]
Repro:

```
echo '' > ~.deps.clj/1.11.1.1273/ClojureTools/clojure-tools-1.11.1.1273.jar
$ bb -Sforce -Sdeps '{:deps {medley/medley {:mvn/version "1.3.0"}}}' -e nil
Error: Could not find or load main class clojure.main
Caused by: java.lang.ClassNotFoundException: clojure.main
Exception in thread "main" clojure.lang.ExceptionInfo:  babashka.process.Process@5e086cbc
	at babashka.process$check.invokeStatic(process.cljc:111)
	at babashka.process$shell.invokeStatic(process.cljc:646)
	at babashka.impl.deps$add_deps$fn__27036.invoke(deps.clj:100)
	at borkdude.deps$_main.invokeStatic(deps.clj:937)
	at borkdude.deps$_main.doInvoke(deps.clj:772)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at babashka.impl.deps$add_deps$fn__27043$fn__27044.invoke(deps.clj:106)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1990)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1990)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at babashka.impl.deps$add_deps$fn__27043.invoke(deps.clj:106)
	at babashka.impl.deps$add_deps.invokeStatic(deps.clj:106)
	at babashka.main$exec$fn__31809.invoke(main.clj:870)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1990)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1990)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at babashka.main$exec.invokeStatic(main.clj:822)
	at babashka.main$main.invokeStatic(main.clj:1165)
	at babashka.main$main.doInvoke(main.clj:1122)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at babashka.main$_main.invokeStatic(main.clj:1198)
	at babashka.main$_main.doInvoke(main.clj:1190)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at babashka.main.main(Unknown Source)
```

cc @pesterhazy

**Comment by pesterhazy** [comment]
Awesome! Looks like a great solution
