### ISSUE TITLE
bb --version could run without a JVM

### ISSUE THREAD

**Issue by ieugen** [babashka/babashka#1686]
This surprised me. 
I did not expect bb to require JVM. 

**version**
1.3.183

**platform**

Was Windows but might be the same on others.

**problem**

`bb` fails to run without a JVM and throws exception.
if there is a bb.edn with deps . 

No bb command works I believe. 

This was discussed https://clojurians.slack.com/archives/CLX41ASCS/p1712827785933789

**repro**

``` shell
# create a container
 docker run -ti debian bash 
# install curl
apt update && apt install -y curl vim 

# install bb via install scritp

# create a bb.edn file with
cat bb.edn
{:min-bb-version "1.0.0"
 :paths ["script"]
 :deps {amperity/vault-clj {:mvn/version "1.1.3"}
        io.github.ieugen/compoje {:git/sha "4fad03af73ac80ec6a25794c410f3a4abef46311"}}
}

# run bb
root@e0c7668bed59:/# bb
Exception in thread "main" java.lang.Exception: Couldn't find 'java'. Please set JAVA_HOME.
	at borkdude.deps$get_java_cmd.invokeStatic(deps.clj:281)
	at borkdude.deps$_main.invokeStatic(deps.clj:902)
	at borkdude.deps$_main.doInvoke(deps.clj:882)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at babashka.impl.deps$add_deps$fn__27345$fn__27346.invoke(deps.clj:113)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1990)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1990)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at babashka.impl.deps$add_deps$fn__27345.invoke(deps.clj:113)
	at babashka.impl.deps$add_deps.invokeStatic(deps.clj:113)
	at babashka.main$exec$fn__32212.invoke(main.clj:872)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1990)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1990)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at babashka.main$exec.invokeStatic(main.clj:824)
	at babashka.main$main.invokeStatic(main.clj:1201)
	at babashka.main$main.doInvoke(main.clj:1148)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at babashka.main$_main$f__32337__auto____32347.invoke(main.clj:1240)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base@21.0.2/java.lang.Thread.runWith(Thread.java:1596)
	at java.base@21.0.2/java.lang.Thread.run(Thread.java:1583)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:833)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:211)
Exception in thread "main" java.lang.NullPointerException
	at clojure.lang.RT.intCast(RT.java:1221)
	at babashka.main$_main.invokeStatic(main.clj:1240)
	at babashka.main$_main.doInvoke(main.clj:1226)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at babashka.main.main(Unknown Source)
	at java.base@21.0.2/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
```

**expected behavior**

- bb should run ?! 
- bb should display a friendlier error
- bb should not depend on JVM :D 
 
I don't think any bb command works.

**Comment by borkdude** [comment]
`bb --version` could run without a JVM, but anything that requires the dependencies to be in place will still require it. Will fix `--version` to run without a JVM and will check if there are more commands that could run without a JVM

**Comment by bobisageek** [comment]
From a preliminary skim, I think it'd be possible to do `version`, `help`, `describe`, and possibly `print-deps` without fetching any deps. Additionally, it _might_ be possible to do `list-tasks` (I need to dig deeper into that code), but I think that would potentially break fetching task docs where a task happens to call a function from a required dep.
To minimize restructuring, I was thinking about an alternate path in `main/main`, where if any of the candidate flags are true, call a different function from `main/exec` that takes a fast path and foregoes fetching any deps.

**Comment by borkdude** [comment]
Just the ones mentioned on the first line are good enough to me.
