### ISSUE TITLE
Can't use a lambda in a babashka's task

### ISSUE THREAD

**Issue by igajsin** [babashka/babashka#1687]
**version**

```
 bb --version
babashka v1.3.189
```

**platform**

```
uname -a
Linux pas 6.7.11 #1 SMP PREEMPT_DYNAMIC 1 x86_64 GNU/Linux
```

**problem**

I've tried to use an anonymous function in a babashka's thrush combinator. The code that works with a regular clojure and fail in the babashka. I'm not sure is it bug or an intended behaviour to be honest.

**repro**

The code, that works in clojure

```clojure
(defn fib [n] (if (< n 2) n (+ (fib (- n 1)) (fib (- n 2)))))
(dotimes [n 8] (->> (fib n) (#(println n ": " %1))))
```

dotimes makes number and the thursh combinator counts the n'th fib number of it and print in the 'i: fib(i)' form. Easy. But what happened if I put it inside my bb.edn?

```clojure
{:tasks
 {
  fib-up-to
  (dotimes [n (Integer/parseInt (first *command-line-args*))]
    (time (->> (shell {:out :string} "./fib.sh" n) :out (#(println %1)))))
 }
}
```
There is the stacktrace
```
bb tasks
Error during loading bb.edn:
Exception in thread "main" java.lang.RuntimeException: No dispatch macro for: (
        at clojure.lang.Util.runtimeException(Util.java:221)
        at clojure.lang.EdnReader$DispatchReader.invoke(EdnReader.java:552)
        at clojure.lang.EdnReader.readDelimitedList(EdnReader.java:757)
        at clojure.lang.EdnReader$ListReader.invoke(EdnReader.java:654)
        at clojure.lang.EdnReader.readDelimitedList(EdnReader.java:757)
        at clojure.lang.EdnReader$ListReader.invoke(EdnReader.java:654)
        at clojure.lang.EdnReader.readDelimitedList(EdnReader.java:757)
        at clojure.lang.EdnReader$ListReader.invoke(EdnReader.java:654)
        at clojure.lang.EdnReader.readDelimitedList(EdnReader.java:757)
        at clojure.lang.EdnReader$ListReader.invoke(EdnReader.java:654)
        at clojure.lang.EdnReader.readDelimitedList(EdnReader.java:757)
        at clojure.lang.EdnReader$MapReader.invoke(EdnReader.java:680)
        at clojure.lang.EdnReader.readDelimitedList(EdnReader.java:757)
        at clojure.lang.EdnReader$MapReader.invoke(EdnReader.java:680)
        at clojure.lang.EdnReader.read(EdnReader.java:145)
        at clojure.lang.EdnReader.read(EdnReader.java:111)
        at clojure.lang.EdnReader.readString(EdnReader.java:67)
        at clojure.edn$read_string.invokeStatic(edn.clj:46)
        at babashka.main$read_bb_edn.invokeStatic(main.clj:1117)
        at babashka.main$main.invokeStatic(main.clj:1184)
        at babashka.main$main.doInvoke(main.clj:1148)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at babashka.main$_main.invokeStatic(main.clj:1234)
        at babashka.main$_main.doInvoke(main.clj:1226)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at babashka.main.main(Unknown Source)
        at java.base@21.0.2/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
```

**expected behavior**

The code above allows me to run `bb run fib-up-to 7` and get the table of fib numbers.

**Comment by borkdude** [comment]
This is because .edn syntax doesn’t let you write the #(…) notation. Just
use fn or move the code to a .clj file

https://www.michielborkent.nl
https://www.eetvoorjeleven.nu

**Comment by igajsin** [comment]
Thanks, it works.
