### ISSUE TITLE
Error using bb git deps in Github Actions runner

### ISSUE THREAD

**Issue by dcostaras** [babashka/babashka#961]
**version**

`<= 0.3.1`

**platform**

GH runner v2.278.0
Ubuntu 20.04.2 LTS

**problem**

Hopefully you can see this page?
https://github.com/Jordan-River-Advisors/babashka-github-actions-repo/runs/3181316513?check_suite_focus=true

If not:
```
Could not find /home/runner/.deps.clj/1.10.3.855/ClojureTools/clojure-tools-1.10.3.855.jar
Attempting download from https://download.clojure.org/install/clojure-tools-1.10.3.855.zip
Cloning: https://github.com/Jordan-River-Advisors/babashka-github-actions-repo.git
Downloading: org/clojure/clojure/1.10.3/clojure-1.10.3.pom from central
Error building classpath. 
java.lang.NullPointerException
	at clojure.tools.deps.alpha.util.dir$canonicalize.invokeStatic(dir.clj:30)
	at clojure.tools.deps.alpha.util.dir$canonicalize.invoke(dir.clj:25)
	at clojure.tools.deps.alpha.extensions.deps$eval1393$fn__1395.invoke(deps.clj:27)
	at clojure.lang.MultiFn.invoke(MultiFn.java:244)
	at clojure.tools.deps.alpha$expand_deps$children_task__790$fn__792$fn__793.invoke(alpha.clj:403)
	at clojure.tools.deps.alpha.util.concurrent$submit_task$task__505.invoke(concurrent.clj:34)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Error: Process completed with exit code 1.
```

**repro**

https://github.com/Jordan-River-Advisors/babashka-github-actions-repo

**expected behavior**

The bb command outputting `2`

(not a sponsor but I do personally back Open Collective 😅 )

**Comment by dcostaras** [comment]
Just realised the version number inequality is probably not right (I always get prefix inequality wrong!). I meant the error exhibits from `0.3.1` onwards.

**Comment by borkdude** [comment]
@dcostaras I'm closing this as non-specific to babashka, as I can replicate the same problem with clojure + deps.edn.

The problem might be that your dependency refers to itself?

**Comment by dcostaras** [comment]
@borkdude thanks. As I said in the readme on the repo, in real use we do not refer to the same project but a different one so it's not that at least.

**Comment by borkdude** [comment]
If you can make a repro that suggest there is a bug in bb, feel free to reopen. If it’s a bug in tools deps, consider making an issue on ask.clojure.org.

**Comment by dcostaras** [comment]
Mind if I ask what steps you used to repro with `clj` and `deps.edn`? I tried something like `clojure -Sdeps '{:deps {org.clojure/tools.reader {:mvn/version "1.1.1"}}}' -e '(+ 1 1)'` which worked.

**Comment by dcostaras** [comment]
I'm just trying with an actual deps edn file now... sorry, should have tried that too
